import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Topbar from "./component/Topbar";
import Sidebar from "./component/Sidebar";
import Footer from "./component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Laique Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`font-inter ${inter.className} bg-white scroll-smooth`}>
      <body className="m-0 p-0">
      <Topbar />
        <div >
          <main >{children}</main>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
